### ISSUE TITLE
VCRUNTIME140_1D.dll is missing

### ISSUE THREAD

**Issue by EisiaDEV** [jss2a98aj/Starbound-Patch-Helper#1]
but VCRUNTIME140_1D.dll isn't installable.

**Comment by jss2a98aj** [comment]
It looks like due to the way that this is built [Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) is a requirement.

**Comment by XionDEV-214** [comment]
I've already deleted and reinstalled as much as I can't count. ofc, nothing has changed.

I've done everything I can. According to my search, VCRUNTIME140_1D.dll is debugging related file. So if it's a debugging related file, there's no reason for the average user to access debugging, so I think the solution is to remove VCRUNTIME140_1D.dll from dependency.

Also, the program itself is treated malicious by window defender, which will need to be fixed too.

**Comment by jss2a98aj** [comment]
> I've already deleted and reinstalled as much as I can't count. ofc, nothing has changed.
> 
> I've done everything I can. According to my search, VCRUNTIME140_1D.dll is debugging related file. So if it's a debugging related file, there's no reason for the average user to access debugging, so I think the solution is to remove VCRUNTIME140_1D.dll from dependency.

That is unfortunate. It might be an issue with how I was building binaries previously. I have swapped things over to CMake, so hopefully that will resolve the issue next time I upload a build.

> Also, the program itself is treated malicious by window defender, which will need to be fixed too.

Yeah, Windows defender does that with most unsigned files.

**Comment by jss2a98aj** [comment]
[0.1.1](https://github.com/jss2a98aj/Starbound-Patch-Helper/releases/tag/0.1.1) should resolve the `VCRUNTIME140_1D.dll` requirement.
